newline_style = "unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features below
unstable_features = true
comment_width = 100
error_on_line_overflow = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_doc_attributes = true
skip_macro_invocations = ["date", "time", "offset"]
wrap_comments = true
